[mgr]
show_hidden = true

[opener]
edit = [
  { run = "nvim \"$@\"", block = true, for = "unix" }
]
image-viewer = [
	{ run = "gthumb \"$@\"", block = true, desc = "Open with gthumb" }
]
sioyek = [
  { run = 'sioyek "$@"', orphan = true, desc = "Open in Sioyek" }
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { name = "*.md", use = "edit" },
  { name = "*.txt", use = "edit" },
  { name = "*.nix", use = "edit" },
  { name = "*.lua", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.json", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
  { name = "*.sh", use = "edit" },
	{ mime = "image/*", use = "image-viewer" },
  { mime = "application/pdf", use = "sioyek" },
  { mime = "application/epub+zip", use = "sioyek" },
]
